#!/bin/sh

# choose a random wallpaper and set it
#feh --recursive --bg-max --randomize ~/.local/share/BG/*
# TODO: add a function tha in dmenu you can select a random BG or select oneBG or select one
wall=$(find $XDG_DATA_HOME/BG -type f | shuf -n 1)
feh --bg-fill $wall
wal -i $wall > /dev/null

# for dwm
sed -i 'N;$!P;D' $XDG_CACHE_HOME/wal/colors-wal-dwm.h

# for tabbed
sed -i '5,$ d' $XDG_CACHE_HOME/wal/colors-wal-tabbed.h

# for dmenu
light=`sed -n '16p' $XDG_CACHE_HOME/wal/colors`
dark=`sed -n '1p' $XDG_CACHE_HOME/wal/colors`
fg2=`sed -n '2p' $XDG_CACHE_HOME/wal/colors`
fg1=`sed -n '14p' $XDG_CACHE_HOME/wal/colors`
sed -i '/^\t\[SchemeOut.*/a \\t\[SchemeHp\] = { "'$dark'", "'$light'", }, \n\t\[SchemeSelHighlight\] = { "'$fg1'", "'$dark'" }, \n\t\[SchemeNormHighlight\] = { "'$dark'", "'$fg2'"},\n\t\[SchemeMid\] = { "'$light'", "'$dark'" },' $XDG_CACHE_HOME/wal/colors-wal-dmenu.h

# for notifications, add three variables to the xresources generated for pywal
sed -n '3,5p' $XDG_CACHE_HOME/wal/colors.Xresources | sed 's/\*foreground/herbe\.font_color/; s/\*background/herbe\.background_color/; s/\*\.foreground/herbe\.border_color/'


# redo everything
(cd "$SUCKLESS_TEMPLATE/dwm" && sudo make clean install > /dev/null)
(cd "$SUCKLESS_TEMPLATE/tabbed-0.6" && sudo make clean install > /dev/null)
(cd "$SUCKLESS_TEMPLATE/dmenu-5.0" && sudo make clean install > /dev/null)
(cd "$SUCKLESS_TEMPLATE/st-0.8.4" && sudo make clean install > /dev/null)
