#!/usr/bin/sh

case $1 in
	toggle) 
	mpc toggle & notify-send -r 1 "$(mpc | sed -n 2p | sed -e 's/\[//' -e 's/\]//' | cut -d' ' -f 1)" "$(mpc current)";;
	pause)
	mpc toggle & notify-send -r 1 "$(mpc | sed -n 2p | sed -e 's/\[//' -e 's/\]//' | cut -d' ' -f 1)" "$(mpc current)";;
esac
