#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=("$prefix"/**/*.gpg)
password_files=("${password_files[@]#"$prefix"/}")
password_files=("${password_files[@]%.gpg}")

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then

	if [[ -n $WAYLAND_DISPLAY ]]; then
		pass "$password" | head -n 1 | wl-copy
		ydotool type $(pass show "$password" | tail -n +2 | dmenu -p "The password for $password is already copied to your clipboard")
	else
		pass show -c "$password" 2>/dev/null
		xdotool type $(pass show "$password" | tail -n +2 | dmenu -p "The password for $password is already copied to your clipboard")
	fi
	# ydotool type $(pass show "$password" | tail -n +2 | dmenu -p "The password for $password is already copied to your clipboard")
else
	pass show "$password" | {
		IFS= read -r pass
		printf %s "$pass"
	} | $xdotool type
fi
