[package]
name = "calendaradd"
version = "0.1.0"
edition = "2021"
authors = ["Miguel <miguel@debloat.us>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
